# The config
recipe: default.v1

# Configuration for Rasa Natural Language Understanding (NLU) model
language: en

pipeline:
  - name: SpacyNLP
    model: en_core_web_md
    case_sensitive: false
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.2

# Policies for the RASA Core model
policies:
  - name: AugmentedMemoizationPolicy
    max_history: 3
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
    check_for_contradictions: True
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    augmentation_factor: 50