recipe: default.v1
language: en
pipeline:
  - name: SpacyNLP
    model: en_core_web_md
  - name: SpacyTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 70
    random_seed: 2
  - name: EntitySynonymMapper

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100